// Imports the bundled harmonies of the Gospels from pre-generated JSON files
// into harmonies/harmony_parts/harmony_sections/harmony_readings, plus the
// prose each harmony was written with (harmony_section_notes,
// harmony_essays).
//
// harmony_of_the_gospels.json follows the chronological table of contents of
// Robert M. Sutherland's "A Four-Column Parallel and Chronological Harmony of
// the Gospels" (2020, https://ebible.org/eng-web/helps/ParallelGospels.docx),
// which the author's own stated terms permit reproducing with attribution.
// Only the event breakdown and its Scripture references are used here -- 136
// sections, extracted from the document's own table of contents and
// cross-checked chapter-by-chapter against each Gospel's chapter count -- not
// the book's narrative commentary, Greek text, or the WEB verse text it
// quotes (this app already has verse text for every bundled translation).
//
// robertson.json is A. T. Robertson's "A Harmony of the Gospels for Students
// of the Life of Christ" (1922), built on the Broadus Harmony and the
// standard student's harmony of the English Gospels for most of a century.
// Published in 1922 and in the public domain; generated by
// tools/extract-harmony.mjs, which documents what it takes and what it
// leaves. Unlike the first, it carries Robertson's own apparatus: fourteen
// Parts, a place-and-date headnote under most section titles, 163 footnotes,
// and the fourteen "Explanatory Notes on Points of Special Difficulty" those
// footnotes cite.
//
// The two disagree, and are meant to. They divide the life of Christ
// differently and date the same events differently; nothing here reconciles
// them.
use rusqlite::{params, Connection};
use serde::Deserialize;
use std::collections::HashMap;
use std::path::Path;

#[derive(Deserialize)]
struct HarmonyReading {
    book: String,
    chapter_start: i64,
    verse_start: Option<i64>,
    chapter_end: i64,
    verse_end: Option<i64>,
    label: String,
}

#[derive(Deserialize)]
struct HarmonyNote {
    marker: String,
    text: String,
    essay: Option<i64>,
}

#[derive(Deserialize)]
struct HarmonyPart {
    order: i64,
    label: Option<String>,
    title: String,
}

#[derive(Deserialize)]
struct HarmonySection {
    order: i64,
    title: String,
    /// The harmony's own section label, where it numbers them separately
    /// from their position (Robertson's 128a/128b).
    #[serde(default)]
    number: Option<String>,
    /// 1-based index into `parts`, for a harmony that groups its sections.
    #[serde(default)]
    part: Option<usize>,
    #[serde(default)]
    headnote: Option<String>,
    #[serde(default)]
    notes: Vec<HarmonyNote>,
    readings: Vec<HarmonyReading>,
}

#[derive(Deserialize)]
struct HarmonyEssay {
    number: i64,
    title: String,
    paragraphs: Vec<String>,
}

#[derive(Deserialize)]
struct Harmony {
    code: String,
    title: String,
    #[serde(default)]
    author: Option<String>,
    #[serde(default)]
    year: Option<i64>,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    source_note: Option<String>,
    #[serde(default)]
    parts: Vec<HarmonyPart>,
    sections: Vec<HarmonySection>,
    #[serde(default)]
    essays: Vec<HarmonyEssay>,
}

fn load_book_lookup(conn: &Connection) -> anyhow::Result<HashMap<String, i64>> {
    let mut stmt = conn.prepare("SELECT id, name FROM books")?;
    let rows = stmt.query_map([], |r| Ok((r.get::<_, String>(1)?, r.get::<_, i64>(0)?)))?;
    Ok(rows.collect::<Result<HashMap<_, _>, _>>()?)
}

fn import_harmony(
    conn: &Connection,
    book_lookup: &HashMap<String, i64>,
    harmony: Harmony,
    sort_order: i64,
) -> anyhow::Result<usize> {
    conn.execute(
        "INSERT INTO harmonies (code, title, author, year, description, source_note, sort_order)
         VALUES (?1,?2,?3,?4,?5,?6,?7)",
        params![
            harmony.code,
            harmony.title,
            harmony.author,
            harmony.year,
            harmony.description,
            harmony.source_note,
            sort_order,
        ],
    )?;
    let harmony_id = conn.last_insert_rowid();

    // Parts first: a section names the part it belongs to by 1-based index
    // into the file's own list, so the row ids have to exist before sections
    // can point at them.
    let mut part_ids = Vec::with_capacity(harmony.parts.len());
    {
        let mut stmt = conn.prepare(
            "INSERT INTO harmony_parts (harmony_id, sort_order, label, title) VALUES (?1,?2,?3,?4)",
        )?;
        for part in &harmony.parts {
            stmt.execute(params![harmony_id, part.order, part.label, part.title])?;
            part_ids.push(conn.last_insert_rowid());
        }
    }

    let mut insert_section = conn.prepare(
        "INSERT INTO harmony_sections (harmony_id, part_id, sort_order, number, title, headnote)
         VALUES (?1,?2,?3,?4,?5,?6)",
    )?;
    let mut insert_reading = conn.prepare(
        "INSERT INTO harmony_readings
           (section_id, sort_order, book_id, chapter_start, verse_start, chapter_end, verse_end, label)
         VALUES (?1,?2,?3,?4,?5,?6,?7,?8)",
    )?;
    let mut insert_note = conn.prepare(
        "INSERT INTO harmony_section_notes (section_id, sort_order, marker, text, essay_number)
         VALUES (?1,?2,?3,?4,?5)",
    )?;

    let mut count = 0usize;
    for section in &harmony.sections {
        let part_id = match section.part {
            // 1-based, as the file writes it.
            Some(i) => Some(*i.checked_sub(1).and_then(|idx| part_ids.get(idx)).ok_or_else(|| {
                anyhow::anyhow!("{}: section {} names part {i}, which the file does not define", harmony.code, section.order)
            })?),
            None => None,
        };
        insert_section.execute(params![
            harmony_id,
            part_id,
            section.order,
            section.number,
            section.title,
            section.headnote,
        ])?;
        let section_id = conn.last_insert_rowid();

        for (sort_order, reading) in section.readings.iter().enumerate() {
            let book_id = *book_lookup
                .get(&reading.book)
                .ok_or_else(|| anyhow::anyhow!("{}: unknown book {:?}", harmony.code, reading.book))?;
            insert_reading.execute(params![
                section_id,
                sort_order as i64,
                book_id,
                reading.chapter_start,
                reading.verse_start,
                reading.chapter_end,
                reading.verse_end,
                reading.label,
            ])?;
            count += 1;
        }
        for (sort_order, note) in section.notes.iter().enumerate() {
            insert_note.execute(params![section_id, sort_order as i64, note.marker, note.text, note.essay])?;
        }
    }

    let mut insert_essay = conn.prepare(
        "INSERT INTO harmony_essays (harmony_id, number, title, body) VALUES (?1,?2,?3,?4)",
    )?;
    for essay in &harmony.essays {
        insert_essay.execute(params![harmony_id, essay.number, essay.title, essay.paragraphs.join("\n\n")])?;
    }

    Ok(count)
}

/// Bundled harmonies, in the order they appear in the picker. The
/// four-column chronological harmony stays first: it is the one the app
/// shipped with, and its 136 flat sections are the plainer read of the two.
const FILES: &[&str] = &["harmony_of_the_gospels.json", "robertson.json"];

pub fn import(conn: &mut Connection, dir: &Path) -> anyhow::Result<usize> {
    let book_lookup = load_book_lookup(conn)?;

    let mut harmonies = Vec::new();
    for file in FILES {
        let text = std::fs::read_to_string(dir.join(file))?;
        harmonies.push(
            serde_json::from_str::<Harmony>(&text).map_err(|e| anyhow::anyhow!("{file}: {e}"))?,
        );
    }

    let tx = conn.transaction()?;
    // A content.db built before harmonies were a table of their own already
    // holds the first harmony's sections, with no harmony to attach them to.
    // All of this is bundled content rather than anything the reader owns, so
    // the import simply starts the tables over.
    tx.execute("DELETE FROM harmony_readings", [])?;
    tx.execute("DELETE FROM harmony_sections", [])?;

    let mut total = 0usize;
    for (i, harmony) in harmonies.into_iter().enumerate() {
        total += import_harmony(&tx, &book_lookup, harmony, i as i64 + 1)?;
    }
    tx.commit()?;
    Ok(total)
}
