/** Common names and abbreviations for each book, by book id - 1, kept in
 * step with `NAMES` in src-tauri/src/refparse.rs so "Jn 3:16" means the same
 * thing in the Go to box as in the search. */
export const BOOK_ABBREVIATIONS: string[][] = [
  ["genesis", "gen", "ge", "gn"],
  ["exodus", "exod", "exo", "ex"],
  ["leviticus", "lev", "le", "lv"],
  ["numbers", "num", "nu", "nm", "numb"],
  ["deuteronomy", "deut", "deu", "de", "dt"],
  ["joshua", "josh", "jos", "jsh", "josue"],
  ["judges", "judg", "jdg", "jg", "jdgs"],
  ["ruth", "rut", "ru", "rth"],
  ["1samuel", "1sam", "1sa", "1sm", "1s", "1kingdoms"],
  ["2samuel", "2sam", "2sa", "2sm", "2s", "2kingdoms"],
  ["1kings", "1kgs", "1ki", "1kin", "1k", "3kingdoms"],
  ["2kings", "2kgs", "2ki", "2kin", "2k", "4kingdoms"],
  ["1chronicles", "1chron", "1chr", "1ch", "1paralipomenon", "1par"],
  ["2chronicles", "2chron", "2chr", "2ch", "2paralipomenon", "2par"],
  ["ezra", "ezr", "ez", "1esdras"],
  ["nehemiah", "neh", "ne", "2esdras"],
  ["esther", "esth", "est", "es"],
  ["job", "jb"],
  ["psalms", "psalm", "ps", "psa", "pss", "psm", "pslm"],
  ["proverbs", "prov", "pro", "prv", "pr", "prvbs"],
  ["ecclesiastes", "eccles", "eccl", "ecc", "ec", "qoh", "qoheleth", "ecclus"],
  ["songofsolomon", "songofsongs", "song", "sos", "so", "canticles", "cant", "canticleofcanticles", "sg", "sng"],
  ["isaiah", "isa", "is", "isaias"],
  ["jeremiah", "jer", "je", "jr", "jeremias"],
  ["lamentations", "lam", "la"],
  ["ezekiel", "ezek", "eze", "ezk", "ezechiel"],
  ["daniel", "dan", "da", "dn"],
  ["hosea", "hos", "ho", "osee"],
  ["joel", "jl", "joe"],
  ["amos", "am", "amo"],
  ["obadiah", "obad", "ob", "oba", "abdias"],
  ["jonah", "jon", "jnh", "jonas"],
  ["micah", "mic", "mi", "mc", "micheas"],
  ["nahum", "nah", "na"],
  ["habakkuk", "hab", "hb", "habacuc"],
  ["zephaniah", "zeph", "zep", "zp", "sophonias"],
  ["haggai", "hag", "hg", "aggeus"],
  ["zechariah", "zech", "zec", "zc", "zach", "zacharias"],
  ["malachi", "mal", "ml", "malachias"],
  ["matthew", "matt", "mat", "mt"],
  ["mark", "mrk", "mar", "mk", "mr"],
  ["luke", "luk", "lk", "lu"],
  ["john", "joh", "jhn", "jn", "jno"],
  ["acts", "act", "ac"],
  ["romans", "rom", "ro", "rm"],
  ["1corinthians", "1cor", "1co"],
  ["2corinthians", "2cor", "2co"],
  ["galatians", "gal", "ga"],
  ["ephesians", "eph", "ephes", "ep"],
  ["philippians", "phil", "php", "pp", "philip"],
  ["colossians", "col", "co"],
  ["1thessalonians", "1thess", "1thes", "1th"],
  ["2thessalonians", "2thess", "2thes", "2th"],
  ["1timothy", "1tim", "1ti", "1tm"],
  ["2timothy", "2tim", "2ti", "2tm"],
  ["titus", "tit", "ti"],
  ["philemon", "philem", "phm", "phlm", "phile"],
  ["hebrews", "heb", "he"],
  ["james", "jas", "jam", "jm"],
  ["1peter", "1pet", "1pe", "1pt", "1p"],
  ["2peter", "2pet", "2pe", "2pt", "2p"],
  ["1john", "1jn", "1jo", "1joh", "1jhn"],
  ["2john", "2jn", "2jo", "2joh", "2jhn"],
  ["3john", "3jn", "3jo", "3joh", "3jhn"],
  ["jude", "jud", "jd"],
  ["revelation", "rev", "re", "rv", "apocalypse", "apoc", "revelations"],
];
