import type { LessonData } from "../course";
import { HIGHLIGHT_TIP, NOTE_TIP } from "./tips";

const ROMANS = 45;

export const WSC_33: LessonData = {
  id: "wsc-33",
  title: "Justification",
  questions: [33],
  intro:
    "How can a guilty person be right with God? The Catechism answers in one sentence, and every phrase of it comes from Paul. In this lesson you read Romans 3 for yourself, weigh its key word in Greek, and set the Catechism's answer beside the Scripture it was drawn from.",
  workspace: {
    passage: { book: ROMANS, chapter: 3, verse: 21 },
    study: ["crossrefs", "confession-for-passage"],
    question: 33,
  },
  steps: [
    {
      id: "before",
      title: "Before you read",
      text: "In a sentence or two: how can a guilty person be right with God? Write what you think now. You will see it again at the end of the unit, beside what you have learned.",
      check: { type: "answer", placeholder: "A guilty person can be right with God by…" },
    },
    {
      id: "observe",
      title: "Read and mark",
      text: "Read Romans 3:21–28 slowly. Highlight every “righteousness” and every “justified”. Notice where the righteousness comes from, and how it is received.",
      tip: HIGHLIGHT_TIP,
      open: { pane: "bible", passage: { book: ROMANS, chapter: 3, verse: 21, to: 28 } },
      check: { type: "highlight", passage: { book: ROMANS, chapter: 3, verse: 21, to: 28 } },
    },
    {
      id: "word",
      title: "The word: dikaioō",
      text: "“Justified” in verse 24 is the Greek δικαιόω. Look at how the New Testament uses it. Does it mean to make a person righteous within, or to declare a person righteous, as a judge does? Notice Luke 7:29, where the people “justified God”.",
      tip: "Word study gathers every place a Greek or Hebrew word is used, with how the KJV translates it.",
      open: { pane: "wordstudy", strongs: "G1344" },
      check: { type: "opened" },
    },
    {
      id: "old-word",
      title: "An old word",
      text: "The Catechism was written in 1647. See how Webster defined “justification” for readers of the King James Bible, and notice the legal sense he puts first.",
      tip: "Webster’s 1828 dictionary defines English as the Bible’s first readers knew it.",
      open: { pane: "webster", word: "justification" },
      check: { type: "opened" },
    },
    {
      id: "scripture",
      title: "Scripture with Scripture",
      text: "Follow the cross references from Romans 3:28 to Galatians 2:16 and Titus 3:7. You will also meet James 2:24: “by works a man is justified, and not by faith only.” Read James 2:14–26. Is James answering the same question as Paul, or showing what living faith looks like?\n\nThe Confession (11.2) puts the two together: faith “is the alone instrument of justification; yet is it not alone in the person justified, but is ever accompanied with all other saving graces, and is no dead faith, but worketh by love.”",
      tip: "Cross references list other verses on the same subject, strongest first. They follow whichever verse you click in the Bible pane.",
      open: { pane: "crossrefs", passage: { book: ROMANS, chapter: 3, verse: 28 } },
      check: { type: "opened" },
    },
    {
      id: "answer",
      title: "The Catechism’s answer",
      text: "Now read Question 33. Find each phrase in what you read: an act of God’s free grace (v. 24), pardon (v. 25), righteousness imputed (4:6), received by faith alone (v. 28).",
      open: { pane: "westminster", doc: "wsc", n: 33 },
      check: { type: "opened" },
    },
    {
      id: "agree",
      title: "Other confessions agree",
      text: "The Heidelberg Catechism (1563) asks the same question: “How art thou righteous before God?” Read its answer, then the Belgic Confession’s Article 23. Reformed churches in Germany, the Netherlands and Britain confessed one gospel.",
      open: { pane: "westminster", doc: "heidelberg", n: 60 },
      openLabel: "Open Heidelberg 60",
      check: { type: "opened" },
    },
    {
      id: "teaching",
      title: "Teaching",
      text: "Alexander Whyte explains the answer phrase by phrase. Read him on Question 33.\n\nThe Confession (11.1) says plainly what justification is not: God justifies “not by infusing righteousness into them, but by pardoning their sins, and by accounting and accepting their persons as righteous: not for anything wrought in them, or done by them, but for Christ’s sake alone; nor by imputing faith itself, the act of believing, or any other evangelical obedience to them, as their righteousness.”",
      open: { pane: "westminster", doc: "wsc", n: 33, commentary: "whyte" },
      openLabel: "Read Whyte on Q33",
      check: { type: "opened" },
    },
    {
      id: "classic",
      title: "A classic reading",
      text: "Thomas Watson preached through the Catechism in the 1660s. Read his sermon on justification from “What is meant by justification?” to the end of “the method of our justification”.",
      open: {
        pane: "book",
        title: "A Body of Divinity",
        find: "What is meant by justification?",
        fallback: { doc: "wsc", n: 33, commentary: "flavel" },
      },
      openLabel: "Open Watson",
      check: { type: "opened" },
    },
    {
      id: "check",
      title: "Check your understanding",
      text: "Four questions on what you have read.",
      check: {
        type: "quiz",
        questions: [
          {
            q: "Is justification an act or a work?",
            choices: ["An act, done once and complete", "A work, carried on through the Christian life"],
            answer: 0,
            why: "Justification is an act (Q33); sanctification is a work (Q35). The Larger Catechism sets the two side by side in Question 77.",
          },
          {
            q: "On what ground does God accept us as righteous?",
            choices: ["Our faith, counted as a good work", "The righteousness of Christ imputed to us", "Our sincere obedience", "The righteousness God works within us"],
            answer: 1,
            why: "“Only for the righteousness of Christ imputed to us” (Q33; Romans 4:6, 2 Corinthians 5:21).",
          },
          {
            q: "What two things does God do in justifying a sinner?",
            choices: ["He pardons all their sins and accepts them as righteous", "He forgives past sins and helps them avoid future ones", "He makes them holy and then forgives them"],
            answer: 0,
            why: "“He pardoneth all our sins, and accepteth us as righteous in his sight.”",
          },
          {
            q: "How is Christ’s righteousness received?",
            choices: ["By faith and good works together", "By baptism", "By faith alone"],
            answer: 2,
            why: "“Received by faith alone” (Romans 3:28, Galatians 2:16). The Larger Catechism (Q73) adds that faith justifies not for any grace in it, but only as the instrument by which we receive Christ.",
          },
        ],
      },
    },
    {
      id: "write",
      title: "Write it",
      text: "Put Question 33 in your own words, as a note on Romans 3:28. Your note stays with the verse, so you will meet it again whenever you read Romans.",
      tip: NOTE_TIP,
      open: { pane: "bible", passage: { book: ROMANS, chapter: 3, verse: 28 } },
      openLabel: "Open Romans 3:28",
      check: { type: "note", passage: { book: ROMANS, chapter: 3, verse: 28 }, tag: "wsc-33" },
    },
    {
      id: "keep",
      title: "Keep it",
      text: "Learn the answer by heart, and the verse it rests on. Memory brings each card back for review just before you would forget it.",
      check: { type: "memory", questions: [33], verse: { book: ROMANS, chapter: 3, verse: 28 } },
    },
    {
      id: "sing",
      title: "Sing",
      text: "Paul cites Psalm 32 in Romans 4:6–8: “Blessed is he whose transgression is forgiven.” Sing it, or read it aloud.",
      open: { pane: "psalter", psalm: 32 },
      openLabel: "Open Psalm 32",
      check: { type: "opened" },
      optional: true,
    },
    {
      id: "pray",
      title: "Pray",
      text: "Pray Psalm 32 back to God: confess your sin plainly, and thank him for the righteousness of Christ that covers it.",
      tip: "The prayer journal keeps your prayers by date; adoration, confession, thanksgiving, supplication is one order to follow.",
      open: { pane: "prayer" },
      openLabel: "Open the prayer journal",
      check: { type: "prayer", tag: "wsc-33" },
    },
  ],
};
